{% set version = "1.2.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-minqa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/minqa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/minqa/minqa_{{ version }}.tar.gz
  sha256: 5941e4b9b01978fc6d9fe24e6ca60cca66883fe9fa6ff3cbfa32aa1ac9db5467

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ compiler('m2w64_fortran') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.9.10
  run:
    - r-base
    - r-rcpp >=0.9.10

test:
  commands:
    - $R -e "library('minqa')"           # [not win]
    - "\"%R%\" -e \"library('minqa')\""  # [win]

about:
  home: http://optimizer.r-forge.r-project.org
  license: GPL-2.0-only
  summary: Derivative-free optimization by quadratic approximation based on an interface to Fortran implementations by M. J. D. Powell.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
